export enum UserRole {
  ADMIN = 'ADMIN',
  SUPPLIER_STORE = 'SUPPLIER_STORE',
  SUPPLIER_FACTORY = 'SUPPLIER_FACTORY',
  CONTRACTOR = 'CONTRACTOR',
  BUYER = 'BUYER',
  DRIVER = 'DRIVER',
}

export enum UserStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  CANCELLED = 'CANCELLED',
}

export enum SubOrderStatus {
  AWAITING_SEPARATION = 'AWAITING_SEPARATION',
  IN_SEPARATION = 'IN_SEPARATION',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  PIX = 'PIX',
  BOLETO = 'BOLETO',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  TERM_PAYMENT = 'TERM_PAYMENT',
}

export enum DeliveryStatus {
  ASSIGNED = 'ASSIGNED',
  COLLECTING = 'COLLECTING',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  CONTRATO_SOCIAL = 'CONTRATO_SOCIAL',
  CNPJ = 'CNPJ',
  INSCRICAO_ESTADUAL = 'INSCRICAO_ESTADUAL',
  CPF = 'CPF',
  CNH_FRENTE = 'CNH_FRENTE',
  CNH_VERSO = 'CNH_VERSO',
  CRLV = 'CRLV',
  SELFIE_DOCUMENTO = 'SELFIE_DOCUMENTO',
  COMPROVANTE_RESIDENCIA = 'COMPROVANTE_RESIDENCIA',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
}

export enum VehicleType {
  MOTO = 'MOTO',
  CARRO = 'CARRO',
  VAN = 'VAN',
  CAMINHONETE = 'CAMINHONETE',
  CAMINHAO = 'CAMINHAO',
}
